export enum Icons {
    ADD = "plus",
    CANCEL = "cross",
    COLLAPSE = "chevron-right",
    COPY = "copy",
    DELETE = "trash",
    DICE = "dices",
    DONE = "checkmark",
    EDIT = "edit",
    LOADING = "loader-2",
    MINUS = "minus-square",
    NEXT = "arrow-big-right",
    PARENT_FOLDER = "folder-closed",
    PLUS = "plus-square",
    PREVIOUS = "arrow-big-left",
    REMOVE = "delete",
    RESET = "reset",
    SAVE = "save",
    SUBFOLDER = "folder-tree",
    WARNING = "alert-triangle"
}
